# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4189e7ef66987d66aff657f276be0641da7b631edd9919238a164e3035dc14b81318adb4f0cfc8368ea7879c4941fa6bba511ba58fa7ea9abaae5522ac24a2af

test:
  secret_key_base: a0c90a560b4de50b9a5f401820890e6c9f16b8d71e2fc03f2e5aa2ae10949036af5c46312be7978a629d3f997658d2b4c8953a32749210968aee93c75c82af68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
